test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -553,31 +553,48 @@ jobs:
       #       - run:
       #     name: update-npm
       #     command: 'sudo npm install -g npm@latest'
-      # - run:
-      #     name: install-snyk
-      #     command: ''   
-      # - run: # run snyk auth - authenticate snyk use environment variables to add token
-      #     name: snyk auth
-      #     command: 
-      # - run: # run snyk test - run snyk testa
-      #     name: snyk test
-      #     command: snyk test  --severity-threshold=low --org=Splunk --file=requirements_dev.txt --package-manager=pip --command=python3 --json-file-output=/root/project/test-results/snyk-scan.json --debug 
-      - snyk/scan:
-          additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
-          target-file: 'requirements_dev.txt'
-          fail-on-issues: false
-      - snyk/scan:
-          additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
-          target-file: 'requirements_addon_specific.txt'
-          fail-on-issues: false
-      - snyk/scan:
-          additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
-          target-file: 'requirements_py2_dev.txt'
-          fail-on-issues: false
-      - snyk/scan:
-          additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
-          target-file: 'package/lib/requirements.txt'
-          fail-on-issues: false
+      - run:
+          name: install-snyk
+          command: |
+              #!/bin/bash -eo pipefail
+              if [[ ! -x "/usr/local/bin/snyk" ]]; then
+                if [[ "linux" == "alpine" && "true" == "true" ]]; then
+                  apk add -q --no-progress --no-cache curl wget libstdc++ sudo
+                fi
+                curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" | grep linux | cut -d '"' -f 4 | xargs -n 1 curl -LO
+                sha256sum -c snyk-linux.sha256
+                sudo mv snyk-linux /usr/local/bin/snyk
+                sudo chmod +x /usr/local/bin/snyk
+              fi
+              snyk config set disableSuggestions=true
+              snyk auth $SNYK_TOKEN   
+      - run: # run snyk auth - authenticate snyk use environment variables to add token
+          name: snyk auth
+          command: snyk auth $SNYK_TOKEN
+      - run: # run snyk test - run snyk testa
+            name: snyk test
+            command: | 
+              snyk test  --severity-threshold=low  --file=requirements_dev.txt --package-manager=pip --skip-unresolved --command=python3 --json-file-output=/root/project/test-results/snyk-scan.json
+              snyk test  --severity-threshold=low  --file=requirements_addon_specific.txt --package-manager=pip --skip-unresolved --command=python3 --json-file-output=/root/project/test-results/snyk-scan.json || true
+              snyk test  --severity-threshold=low  --file=requirements_py2_dev.txt --package-manager=pip --skip-unresolved --command=python3 --json-file-output=/root/project/test-results/snyk-scan.json || true
+              snyk test  --severity-threshold=low  --file=package/lib/requirements.txt --package-manager=pip --skip-unresolved --command=python3 --json-file-output=/root/project/test-results/snyk-scan.json || true
+
+      # - snyk/scan:
+      #     additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
+      #     target-file: 'requirements_dev.txt'
+      #     fail-on-issues: false
+      # - snyk/scan:
+      #     additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
+      #     target-file: 'requirements_addon_specific.txt'
+      #     fail-on-issues: false
+      # - snyk/scan:
+      #     additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
+      #     target-file: 'requirements_py2_dev.txt'
+      #     fail-on-issues: false
+      # - snyk/scan:
+      #     additional-arguments: "--package-manager=pip --skip-unresolved --command=python3"
+      #     target-file: 'package/lib/requirements.txt'
+      #     fail-on-issues: false
       - store_artifacts:
           path: test-results
           destination: test-results
